---
homebrew_installed_packages:
  - opam
  - pkg-config
  - capnp
  - gmp 
  - libev 
  - lz4

homebrew_cask_apps:
  - osxfuse

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_folders_additional:
  - /usr/local/share/man/man8